version: '3'
services:
    mariadb:
        restart: unless-stopped
        image: 'mariadb:10'
        ports:
            - '127.0.0.1:3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'overnites'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
        volumes:
            - 'mariadb:/var/lib/mysql'
        networks:
            - network
    node:
        restart: unless-stopped
        build:
            dockerfile: 'Dockerfile'
            target: dev
        volumes:
            - './:/usr/src/app'
        ports:
            - '3000:3000'
        networks:
            - network
networks:
    network:
        driver: bridge
volumes:
    mariadb:
        driver: local
