name: overnites

on: [pull_request, push]

jobs:
    semantic-pull-request:
        uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1
    test:
        runs-on: ubuntu-latest
        env:
            HOST: 127.0.0.1
            DATABASE_URL: "mysql://root:password@localhost:3306/overnites"
            DATABASE_URL_TEST: "mysql://root:password@localhost:3306/overnites"
        steps:
            - uses: actions/checkout@v2

            - name: Setup MariaDB server
              uses: getong/mariadb-action@v1.1
              with:
                  mysql database: "overnites"
                  mysql root password: "password"

            - name: Install node
              uses: actions/setup-node@v2
              with:
                  node-version: "19"
                  cache: "npm"

            - name: Install npm modules
              run: npm install

            - name: Run prisma migrations & generate prisma client
              run: npx prisma migrate dev

            - name: Run tests
              run: npm run test
